// Generates app/constants/config.js from environment variables at build time.
// This keeps the real config.js out of the (now public) repo, while still
// letting local dev and Vercel builds produce a working config file.
const fs = require('fs');
const path = require('path');
 
const API_URL = process.env.API_URL || 'https://www.biteandco.id/api/v1';
const GOOGLE_MAPS_API_KEY = process.env.GOOGLE_MAPS_API_KEY || '';
 
if (!process.env.API_URL) {
  console.warn('[generate-config] Warning: API_URL env var not set, falling back to default.');
}
 
const fileContent = `// AUTO-GENERATED by scripts/generate-config.js — do not edit directly.
// Edit environment variables in Vercel (or your local .env) instead.
const config = {
  API_URL: "${API_URL}",
  GOOGLE_MAPS_API_KEY: "${GOOGLE_MAPS_API_KEY}",
  DEV_MODE: __DEV__,
  LOG_LEVEL: __DEV__ ? 'debug' : 'error',
};
 
export default config;
`;
 
const outPath = path.join(__dirname, '..', 'app', 'constants', 'config.js');
fs.writeFileSync(outPath, fileContent);
console.log(`[generate-config] Wrote ${outPath}`);